spring.datasource.url=jdbc:postgresql://localhost:5432/prosync_db
spring.datasource.username=postgres
spring.datasource.password=220290171802
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jackson.serialization.write-dates-as-timestamps=false

server.port=8081

# JWT — cambiar en producción
jwt.secret=UHJvU3luY1NlY3JldEtleUZvckpXVEF1dGgyMDI2UHJvU3luYw==
jwt.expiration=86400000
