spring.datasource.url=jdbc:postgresql://admin_prosync:Wdh1idAqre1axo7PSRnIBFSjIKzcv7bg@dpg-d860mrb7uimc73bro2ug-a.ohio-postgres.render.com/prosync_db_agfz 
spring.datasource.username=admin_prosync
spring.datasource.password=Wdh1idAqre1axo7PSRnIBFSjIKzcv7bg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# none = no DDL changes, no validation. El esquema lo gestiona 001_initial_schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jackson.serialization.write-dates-as-timestamps=false

server.port=8081
